# This file contains values from Cookiecutter

default_context:
  project_name: "conda-activator-py"
  project_description: "Awesome `conda-activator-py` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "samesense"
  license: "MIT"
  version: "0.1.0"
  github_name: "samesense"
  email: "samesense@gmail.com"
